#!/bin/bash
set -e -u -o pipefail



get_log () {

  mkdir -p ./logs
  docker-compose run  --rm  ingest bash -c "/opt/scripts/copy_logs.sh"
}


build () {

  mkdir -p ./logs
  rm -rf ./logs/*

  mkdir -p ./tmp
  rm -rf ./tmp/*

  docker-compose build --no-cache ingest
  docker-compose build --no-cache spark-app
}




spark_app () {

  #Prime logs for cold start
  docker-compose  run --rm spark-app

}


shell () {
  #Prime logs for cold start
  docker-compose  run --rm spark-shell
}


run (){
  spark_app
}

"$@"


