#!/bin/bash
set -e -uf -o pipefail


build () {

  mkdir -p ./logs
  rm -rf ./logs/*
  docker-compose build ingest
  docker-compose build spark-app
}


get_log () {

  mkdir -p ./logs
  docker-compose build ingest
  docker-compose run  ingest bash -c "/opt/scripts/copy_logs.sh"
}


spark_app () {

  #Prime logs for cold start
  get_log
  docker-compose  run spark-app

}


spark_shell () {
  #Prime logs for cold start
  docker-compose  run spark-shell
}

"$@"


