version: "3.9"
services:
  ingest:
    user: 5000:5000
    build:
      context: ./ingest
      dockerfile: Dockerfile
    working_dir: "/home/appuser"
    command: ["cron",]
    volumes:
      - ./logs:/local/logs
      - ./spark_app:/opt/spark_app
      - ./tmp:/tmp
  spark-app:
    user: 5000:5000
    build:
      context: ./spark_app
      dockerfile: Dockerfile
    volumes:
      - ./logs:/local/logs
      - ./spark_app:/opt/spark_app
      - ./tmp:/tmp
    working_dir: "/home/appuser"
    depends_on:
      - ingest
    command: ["spark-app", "run"]
  spark-shell:
    user: 5000:5000
    build:
      context: ./spark_app
      dockerfile: Dockerfile
    entrypoint: ["/bin/bash"]
    volumes:
      - ./logs:/local/logs
      - ./spark_app:/opt/spark_app
      - ./tmp:/tmp
    working_dir: "/home/appuser"
    depends_on:
      - ingest