version: "3.9"
services:
  ingest:
    user: 5000:5000
    build:
      context: ./ingest
      dockerfile: Dockerfile
    working_dir: "/opt/spark_app"
    volumes:
      - ./logs:/local/logs
      - ./spark_app:/opt/spark_app
      - ./tmp:/tmp
  spark-app:
    user: 5000:5000
    build:
      context: ./spark_app
      dockerfile: Dockerfile
    volumes:
      - ./logs:/local/logs
      - ./spark_app:/opt/spark_app
      - ./tmp:/tmp
    working_dir: "/opt/spark_app"
    depends_on:
      - ingest
  spark-shell:
    user: 5000:5000
    build:
      context: ./spark_app
      dockerfile: Dockerfile
    volumes:
      - ./logs:/local/logs
      - ./spark_app:/opt/spark_app
      - ./tmp:/tmp
    command: "bash"
    working_dir: "/opt/spark_app"
    depends_on:
      - ingest